### ISSUE TITLE
Add assessor - no info and save causes app to crash

### ISSUE THREAD

**Issue by andyjones81** [DFE-Digital/dops-sas#39]
The validation handler is missing on the Admin > Administrators > Add 

Sign in as admin
Go to Administrators
Don't enter any info and click save and return
App crashes

```
/service-assessment-service/app/controllers/adminController.js:746
                assessment, assessors,
                ^
ReferenceError: assessment is not defined
    at exports.p_addadmin (/service-assessment-service/app/controllers/adminController.js:746:17)
    at Layer.handle [as handle_request] (/service-assessment-service/node_modules/express/lib/router/layer.js:95:5)
    at next (/service-assessment-service/node_modules/express/lib/router/route.js:149:13)
    at middleware (/service-assessment-service/node_modules/express-validator/src/middlewares/check.js:16:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Expected

Validation should be triggered to stop this happeneing

**Comment by andyjones81** [comment]
No longer an issues
